import type { CodegenConfig } from "@graphql-codegen/cli";

/**
 * GraphQL Codegen config for the Zenland interface.
 *
 * We keep this "internal" to the repo (not a published SDK yet) so the schema
 * can evolve quickly, while still giving us strong typing + DRY operations.
 */
const config: CodegenConfig = {
  /**
   * Use the repo-local schema file generated by Ponder.
   *
   * Why: codegen remains deterministic and doesn't require the indexer dev
   * server to be running.
   *
   * When you change the indexer schema, regenerate it via:
   *   (cd v2/indexer && npm run codegen)
   */
  schema: "../indexer/generated/schema.graphql",
  documents: ["./lib/indexer/**/*.graphql"],
  generates: {
    "./lib/indexer/__generated__/": {
      preset: "client",
      presetConfig: {
        // No framework bindings here; just typed documents + helpers.
        fragmentMasking: false,
      },
    },
  },
  ignoreNoDocuments: true,
};

export default config;
